// All icons come from Lucide (lucide.dev). Names here are the short aliases used across the app.
import {
  ArrowDown,
  Bluetooth,
  MessageCircle,
  Quote,
  Heart,
  Scale,
  Hourglass,
  Activity,
  ArrowLeftRight,
  ArrowUp,
  Calendar,
  ChartLine,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Cloud,
  Copy,
  Download,
  Dumbbell,
  Ellipsis,
  FileText,
  Flame,
  Folder,
  History,
  Link2,
  List,
  Medal,
  Minus,
  Pencil,
  Play,
  Plus,
  Search,
  SlidersHorizontal,
  SquarePlay,
  Target,
  Timer,
  Trash2,
  Unlink2,
  Upload,
  X,
  type LucideIcon,
} from 'lucide-preact'

const ICONS = {
  plus: Plus,
  check: Check,
  x: X,
  down: ChevronDown,
  minimize: ChevronDown,
  left: ChevronLeft,
  right: ChevronRight,
  more: Ellipsis,
  search: Search,
  timer: Timer,
  trash: Trash2,
  pencil: Pencil,
  play: Play,
  video: SquarePlay,
  dumbbell: Dumbbell,
  history: History,
  list: List,
  sliders: SlidersHorizontal,
  up: ArrowUp,
  downArrow: ArrowDown,
  swap: ArrowLeftRight,
  link: Link2,
  unlink: Unlink2,
  note: FileText,
  copy: Copy,
  medal: Medal,
  flame: Flame,
  cloud: Cloud,
  download: Download,
  upload: Upload,
  folder: Folder,
  chart: ChartLine,
  calendar: Calendar,
  minus: Minus,
  target: Target,
  bluetooth: Bluetooth,
  coach: MessageCircle,
  quote: Quote,
  heart: Heart,
  scale: Scale,
  fast: Hourglass,
  activity: Activity,
} satisfies Record<string, LucideIcon>

export type IconName = keyof typeof ICONS

export function Icon({ name, size = 20, class: cls, stroke = 2 }: { name: IconName | string; size?: number; class?: string; stroke?: number }) {
  const C = ICONS[name as IconName]
  if (!C) return null
  return <C class={'icon ' + (cls || '')} size={size} strokeWidth={stroke} aria-hidden="true" fill={name === 'play' ? 'currentColor' : 'none'} />
}
