// All icons come from Lucide (lucide.dev). Names here are the short aliases used across the app.
import {
  Layers,
  LibraryBig,
  Eye,
  EyeOff,
  LogOut,
  PersonStanding,
  Star,
  Share2,
  UserPlus,
  Users,
  ChevronsUpDown,
  ArrowDown,
  Utensils,
  TrendingDown,
  TrendingUp,
  Zap,
  Recycle,
  Droplet,
  Clock,
  CalendarDays,
  LayoutList,
  StickyNote,
  Bluetooth,
  MessageCircle,
  Brain,
  Sparkles,
  Quote,
  Heart,
  Scale,
  Hourglass,
  Activity,
  ArrowLeftRight,
  ArrowUp,
  Calendar,
  ChartLine,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Cloud,
  Copy,
  Download,
  Dumbbell,
  Trophy,
  CalendarCheck2,
  Sun,
  TriangleAlert,
  HeartPulse,
  Ellipsis,
  FileText,
  Flame,
  Folder,
  History,
  Link2,
  List,
  Medal,
  Minus,
  Pencil,
  Play,
  Plus,
  Search,
  SlidersHorizontal,
  SquarePlay,
  Target,
  Timer,
  Trash2,
  Unlink2,
  Upload,
  X,
  Pause,
  ArrowRightLeft,
  type LucideIcon,
} from 'lucide-preact'

const ICONS = {
  plus: Plus,
  check: Check,
  x: X,
  down: ChevronDown,
  minimize: ChevronDown,
  left: ChevronLeft,
  right: ChevronRight,
  more: Ellipsis,
  search: Search,
  timer: Timer,
  trash: Trash2,
  pencil: Pencil,
  play: Play,
  video: SquarePlay,
  dumbbell: Dumbbell,
  trophy: Trophy,
  log: CalendarCheck2,
  sun: Sun,
  alert: TriangleAlert,
  cardio: HeartPulse,
  history: History,
  list: List,
  sliders: SlidersHorizontal,
  up: ArrowUp,
  downArrow: ArrowDown,
  swap: ArrowLeftRight,
  link: Link2,
  unlink: Unlink2,
  note: FileText,
  copy: Copy,
  medal: Medal,
  flame: Flame,
  cloud: Cloud,
  download: Download,
  upload: Upload,
  folder: Folder,
  chart: ChartLine,
  calendar: Calendar,
  minus: Minus,
  target: Target,
  bluetooth: Bluetooth,
  coach: MessageCircle,
  brain: Brain,
  sparkles: Sparkles,
  quote: Quote,
  heart: Heart,
  scale: Scale,
  fast: Hourglass,
  activity: Activity,
  utensils: Utensils,
  trendDown: TrendingDown,
  trendUp: TrendingUp,
  zap: Zap,
  recycle: Recycle,
  droplet: Droplet,
  clock: Clock,
  wheels: ChevronsUpDown,
  logout: LogOut,
  mobility: PersonStanding,
  star: Star,
  share: Share2,
  invite: UserPlus,
  people: Users,
  calendarDays: CalendarDays,
  layoutList: LayoutList,
  sticky: StickyNote,
  program: Layers,
  library: LibraryBig,
  eye: Eye,
  eyeOff: EyeOff,
  pause: Pause,
  switchSides: ArrowRightLeft,
} satisfies Record<string, LucideIcon>

export type IconName = keyof typeof ICONS

export function Icon({ name, size = 20, class: cls, stroke = 2 }: { name: IconName | string; size?: number; class?: string; stroke?: number }) {
  const C = ICONS[name as IconName]
  if (!C) return null
  return <C class={'icon ' + (cls || '')} size={size} strokeWidth={stroke} aria-hidden="true" fill={name === 'play' ? 'currentColor' : 'none'} />
}
