const { chromium } = require('/opt/node22/lib/node_modules/playwright')
;(async () => {
  const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' })
  const p = await b.newPage({ viewport: { width: 390, height: 844 }, hasTouch: true, colorScheme: 'dark' })
  const log = (...a) => console.log(...a)
  await p.goto('http://localhost:4173/#/history'); await p.waitForTimeout(1200)
  const [fc] = await Promise.all([p.waitForEvent('filechooser'), p.locator('.head-import').click()])
  await fc.setFiles(process.argv[2]); await p.waitForTimeout(600)
  await p.locator('.modal .btn-primary').click(); await p.waitForTimeout(1500)
  log('on', p.url())
  await p.locator('[aria-label="Back"], .back, .icon-btn').first().click(); await p.waitForTimeout(1200)
  log('after back (from import):', p.url())
  await p.locator('.workout-card').first().click(); await p.waitForTimeout(1200)
  log('opened', p.url())
  await p.locator('[aria-label="Back"]').first().click(); await p.waitForTimeout(1200)
  log('after back (from list):', p.url())
  await b.close()
})()
