const { chromium } = require('/opt/node22/lib/node_modules/playwright')
const { installFakeClaude } = require('/home/user/Workout-tracker/qa/fake-claude.cjs')
const S = process.argv[2]
;(async () => {
  const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' })
  const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, isMobile: true, hasTouch: true, colorScheme: 'dark', recordVideo: { dir: S + '/vid', size: { width: 390, height: 844 } } })
  await installFakeClaude(ctx, { store: new Map(), sample: async () => ({ text: '{}' }) })
  const p = await ctx.newPage()
  const errs = []; p.on('pageerror', (e) => errs.push(e.message))
  await p.goto('http://localhost:4173/#/train'); await p.waitForSelector('.checkin'); await p.waitForTimeout(1500)
  const box = await p.locator('.checkin').boundingBox()
  console.log('checkin y', Math.round(box.y), Math.round(box.height))
  const row = p.locator('.checkin-opts').first()
  await row.locator('button', { hasText: 'Poor' }).tap(); await p.waitForTimeout(1300)
  await row.locator('button', { hasText: 'Good' }).tap(); await p.waitForTimeout(1500)
  console.log('track head', await p.evaluate(() => { const h = document.querySelector('.checkin-opts .gt-head'); const on = document.querySelector('.checkin-opts > .on'); const a = h.getBoundingClientRect(), o = on.getBoundingClientRect(); return [Math.round(a.x - o.x), Math.round(a.width - o.width), getComputedStyle(h).backgroundColor, getComputedStyle(on).color] }))
  console.log('errors', errs)
  await ctx.close(); await b.close()
})()
