const { chromium } = require('/opt/node22/lib/node_modules/playwright')
;(async () => {
  const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' })
  const p = await b.newPage({ viewport: { width: 390, height: 844 }, hasTouch: true, colorScheme: 'dark' })
  await p.goto('http://localhost:4173/qa-host-blank')
  await p.setContent('<body style="margin:0"><iframe id="f" sandbox="allow-scripts allow-same-origin allow-forms allow-popups" style="border:0;width:390px;height:844px" src="http://localhost:4173/#/train"></iframe></body>')
  await p.waitForTimeout(2000)
  const f = p.frameLocator('#f'); const fr = p.frame({ url: /4173/ })
  await f.locator('[aria-label="Settings"]').first().click(); await p.waitForTimeout(1200)
  console.log('opened', await fr.evaluate(() => location.hash))
  await f.locator('[aria-label="Back"]').first().click(); await p.waitForTimeout(1500)
  console.log('after back', await fr.evaluate(() => location.hash), 'title', await f.locator('h1').first().innerText())
  await b.close()
})()
