const { chromium } = require('/opt/node22/lib/node_modules/playwright')
const { installFakeClaude } = require('/home/user/Workout-tracker/qa/fake-claude.cjs')
;(async () => {
  const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' })
  const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true })
  await installFakeClaude(ctx, { store: new Map(), sample: async (i) => ({ text: typeof i === 'string' ? JSON.stringify({ focus: 'x', targets: [], takeaway: 'ok' }) : 'ok' }) })
  const p = await ctx.newPage()
  p.on('console', (m) => m.text().startsWith('DBG') && console.log(m.text()))
  await p.goto('http://localhost:4173/#/train'); await p.waitForTimeout(1800)
  await p.locator('.routine-card').first().locator('button', { hasText: 'Start' }).tap()
  await p.waitForSelector('.live')
  await p.locator('.ex-card').first().locator('input').nth(0).fill('16')
  await p.locator('.ex-card').first().locator('input').nth(1).fill('10')
  await p.locator('.ex-card').first().locator('.check').first().tap()
  await p.evaluate(() => {
    new MutationObserver((ms) => { for (const m of ms) for (const n of m.removedNodes) if (n.nodeType === 1 && (n.matches?.('.fb-card,.screen') || n.querySelector?.('.fb-card'))) console.log('DBG removed', n.className, location.hash, performance.now() | 0) }).observe(document.body, { childList: true, subtree: true })
  })
  await p.locator('.live-head .btn-primary').tap()
  await p.waitForTimeout(400)
  const sheetBtn = p.locator('.sheet-foot .btn-primary'); if (await sheetBtn.count()) await sheetBtn.tap()
  await p.waitForSelector('.fb-card'); console.log('DBG fb visible', await p.evaluate(() => performance.now() | 0))
  await p.waitForTimeout(3000)
  console.log('DBG fb count', await p.locator('.fb-card').count(), await p.evaluate(() => location.hash))
  await b.close()
})()
