const { chromium } = require('/opt/node22/lib/node_modules/playwright')
const { installFakeClaude } = require('/home/user/Workout-tracker/qa/fake-claude.cjs')
const S = process.argv[2]
;(async () => {
  const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' })
  const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, isMobile: true, hasTouch: true, colorScheme: 'dark', recordVideo: { dir: S + '/vid', size: { width: 390, height: 844 } } })
  await installFakeClaude(ctx, { store: new Map(), sample: async () => ({ text: '{}' }) })
  const p = await ctx.newPage()
  const t0 = Date.now()
  await p.goto('http://localhost:4173/#/train'); await p.waitForTimeout(2000)
  console.log('tab tap at', ((Date.now() - t0) / 1000).toFixed(2))
  await p.locator('.tab').nth(4).tap(); await p.waitForTimeout(2200)
  await p.goto('http://localhost:4173/#/fast'); await p.waitForTimeout(1200)
  console.log('sheet tap at', ((Date.now() - t0) / 1000).toFixed(2))
  await p.locator('button', { hasText: 'Set the start time' }).first().tap(); await p.waitForTimeout(2000)
  await ctx.close(); await b.close()
})()
