const { chromium } = require('/opt/node22/lib/node_modules/playwright')
;(async () => {
  const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' })
  const p = await b.newPage({ viewport: { width: 390, height: 844 } })
  const errs = []; p.on('pageerror', (e) => errs.push(e.message))
  await p.goto('file:///tmp/claude-0/-home-user-Workout-tracker/7e553bdd-1e91-54a0-9d08-274537fd6744/scratchpad/reps.html#/train'); await p.waitForTimeout(1500); console.log('rings:', await p.locator('.today-rings').count()); await p.goto(p.url().split('#')[0] + '#/fast'); await p.waitForTimeout(800)
  console.log('fast screen:', await p.locator('.fast-screen').count())
  await p.locator('.fast-hero .btn-primary').click(); await p.waitForTimeout(400)
  console.log('ring running:', await p.locator('.sr-fg').count())
  await p.goto(p.url().split('#')[0] + '#/history?view=calendar'); await p.waitForTimeout(800)
  console.log('calendar:', await p.locator('.cal-grid').count(), '| fast pill today:', await p.locator('.cal-day.today .cal-fast.live').count())
  console.log(errs.join('\n') || 'no errors')
  await b.close()
})()
