const { chromium } = require('/opt/node22/lib/node_modules/playwright')
;(async () => {
  const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' })
  const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true, colorScheme: 'dark' })
  await ctx.addInitScript(() => localStorage.setItem('reps-token', 'testkey'))
  const p = await ctx.newPage(); const errs = []; p.on('pageerror', (e) => errs.push(e.message))
  await p.goto('http://localhost:3000/#/train'); await p.waitForTimeout(1500)
  await p.screenshot({ path: '/home/user/Workout-tracker/qa/shots12/dark-09-home-fixed.png' })
  await p.locator('.routine-card').first().locator('button', { hasText: 'Start' }).tap()
  await p.waitForSelector('.checklist'); await p.waitForTimeout(500)
  await p.locator('.checklist').first().scrollIntoViewIfNeeded()
  await p.screenshot({ path: '/home/user/Workout-tracker/qa/shots12/dark-10-warmup-videos.png' })
  console.log('video links:', await p.locator('.cl-video').count(), '| first:', await p.locator('.cl-video').first().getAttribute('href'))
  await p.locator('.live-head .btn-primary').tap(); await p.waitForTimeout(400)
  // discard the empty workout
  const disc = p.locator('button', { hasText: /Discard/ }); if (await disc.count()) await disc.first().tap()
  await p.waitForTimeout(300); const conf = p.locator('.dialog .btn-danger, .confirm .btn-danger'); if (await conf.count()) await conf.first().tap()
  console.log(errs.join('\n') || 'no errors'); await b.close()
})()
