// Motivation + coach: quote and win card on Train, coach chat (needs a coach backend), review after a workout, quote settings.
const { chromium } = require(process.env.PLAYWRIGHT || '/opt/node22/lib/node_modules/playwright')
const OUT = __dirname + '/shots8/'
require('fs').mkdirSync(OUT, { recursive: true })
;(async () => {
  const browser = await chromium.launch({ executablePath: process.env.CHROMIUM || '/opt/pw-browsers/chromium' })
  const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true, colorScheme: process.env.SCHEME || 'dark' })
  await ctx.addInitScript(() => localStorage.setItem('reps-token', 'testkey'))
  await ctx.grantPermissions(['clipboard-read', 'clipboard-write'], { origin: process.env.BASE || 'http://localhost:3000' })
  const BASE = process.env.BASE || 'http://localhost:3000'
  const page = await ctx.newPage()
  const errors = []
  page.on('pageerror', (e) => errors.push('pageerror: ' + e.message))
  page.on('console', (m) => m.type() === 'error' && errors.push('console: ' + m.text()))
  const shot = async (n, full) => { await page.waitForTimeout(450); await page.screenshot({ path: OUT + n + '.png', fullPage: !!full }) }
  await page.goto(BASE + '/')
  await page.waitForSelector('.page-head')
  await page.waitForTimeout(1800)
  await shot('01-train', true)
  await page.locator('.tab').nth(4).tap()
  await page.waitForTimeout(800)
  await shot('02-coach-empty')
  await page.locator('.coach-chips .chip').first().tap()
  await page.waitForTimeout(2500)
  await shot('03-coach-answer')
  await page.fill('#coach-input', 'Should I go heavier on goblet squats?')
  await page.locator('.send').tap()
  await page.waitForTimeout(2500)
  await shot('04-coach-followup', true)
  // finish a quick workout and ask the coach about it
  await page.locator('.tab').first().tap()
  await page.locator('button', { hasText: 'Empty workout' }).tap()
  await page.locator('button', { hasText: 'Add exercise' }).tap()
  await page.fill('.sheet input[type=search]', 'hammer curl')
  await page.locator('.pick-row').first().tap()
  await page.locator('.sheet-foot .btn-primary').tap()
  const w = page.locator('input[data-f="weight"]').first(); await w.tap(); await w.fill('11')
  const r = page.locator('input[data-f="reps"]').first(); await r.tap(); await r.fill('10')
  await page.locator('.check').first().tap()
  await page.locator('.live-head .btn-primary').tap()
  await page.locator('.sheet-foot .btn-primary').tap()
  await page.waitForTimeout(800)
  await shot('05-celebrate', true)
  await page.locator('button', { hasText: 'Ask your coach' }).tap()
  await page.waitForTimeout(2500)
  await shot('06-coach-review')
  await page.goto(BASE + '/#/settings')
  await page.waitForTimeout(500)
  await page.locator('.setting', { hasText: 'Your quotes' }).tap()
  await shot('07-quotes', true)
  console.log(errors.join('\n') || 'no errors')
  await browser.close()
})()
