const { chromium } = require(process.env.PLAYWRIGHT || '/opt/node22/lib/node_modules/playwright')
const OUT = __dirname + '/shots4/'
require('fs').mkdirSync(OUT, { recursive: true })
;(async () => {
  const browser = await chromium.launch({ executablePath: process.env.CHROMIUM || '/opt/pw-browsers/chromium' })
  const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true, colorScheme: process.env.SCHEME || 'dark' })
  await ctx.addInitScript(() => localStorage.setItem('reps-token', 'testkey'))
  const page = await ctx.newPage()
  const errors = []
  page.on('pageerror', (e) => errors.push('pageerror: ' + e.message))
  page.on('console', (m) => m.type() === 'error' && errors.push('console: ' + m.text()))
  const shot = async (n, full) => { await page.waitForTimeout(450); await page.screenshot({ path: OUT + n + '.png', fullPage: !!full }) }
  await page.goto('http://localhost:3000/')
  await page.waitForSelector('.plan-card')
  await page.waitForTimeout(1000)
  await page.locator('.plan-card .btn').tap()
  await page.waitForSelector('.live')
  await shot('01-live-start')
  const card = (i) => page.locator('.ex-card').nth(i)
  // 1a set 1: type heavier weight
  const w = card(0).locator('input[data-f="weight"]').first()
  await w.tap(); await w.fill('19')
  await shot('02-typing-restbar-hidden')
  await card(0).locator('.check').first().tap()
  await shot('03-after-1a-next-is-1b')
  await card(1).locator('.check').first().tap()
  await shot('04-after-1b-rest')
  console.log('set2 weight placeholder:', await card(0).locator('input[data-f="weight"]').nth(1).getAttribute('placeholder'))
  // set kind -> warmup on set 3 of card 0
  await card(0).locator('.set-kind').nth(2).tap()
  await page.locator('.action', { hasText: 'Warm-up set' }).tap()
  await shot('05-warmup-moved')
  // undo delete check: delete set 2 of card 1, edit card 1 set 1 reps, undo
  const before = await card(1).locator('.swipe-wrap').count()
  await card(1).locator('.set-kind').nth(1).tap()
  await page.locator('.action', { hasText: 'Delete set' }).tap()
  const r = card(1).locator('input[data-f="reps"]').nth(0)
  await r.tap(); await r.fill('7')
  await page.locator('.toast button').tap()
  const after = await card(1).locator('.swipe-wrap').count()
  console.log('undo rows before/after:', before, after, 'reps kept:', await card(1).locator('input[data-f="reps"]').nth(0).inputValue())
  // finish
  await page.locator('.live-head .btn-primary').tap()
  await shot('06-finish-sheet')
  await page.locator('.pending-card button', { hasText: 'Fill in grey values' }).tap()
  await shot('07-after-fill')
  await page.locator('.sheet-foot .btn-primary').tap()
  await page.waitForTimeout(800)
  await shot('08-summary', true)
  console.log(errors.join('\n') || 'no errors')
  await browser.close()
})()
