const { chromium } = require(process.env.PLAYWRIGHT || '/opt/node22/lib/node_modules/playwright')
const OUT = __dirname + '/shots/'
require('fs').mkdirSync(OUT, { recursive: true })
;(async () => {
  const browser = await chromium.launch({ executablePath: process.env.CHROMIUM || '/opt/pw-browsers/chromium' })
  const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true, colorScheme: process.env.SCHEME || 'dark' })
  const page = await ctx.newPage()
  const errors = []
  page.on('pageerror', (e) => errors.push('pageerror: ' + e.message))
  page.on('console', (m) => m.type() === 'error' && errors.push('console: ' + m.text()))
  const shot = async (n) => { await page.waitForTimeout(400); await page.screenshot({ path: OUT + n + '.png' }) }
  await page.goto('http://localhost:3000/')
  await page.waitForSelector('.page-head')
  await shot('01-train')
  await page.screenshot({ path: OUT + '01b-train-full.png', fullPage: true })
  // Start plan workout
  await page.click('.plan-card .btn')
  await page.waitForSelector('.live')
  await shot('02-live')
  // Fill first set of first exercise
  const w = page.locator('input[data-f="weight"]').first()
  await w.tap(); await w.fill('12')
  const r = page.locator('input[data-f="reps"]').first()
  await r.tap(); await r.fill('10')
  await shot('03-live-typing')
  await page.locator('.check').first().tap()
  await shot('04-set-done')
  // second exercise of superset (row)
  const w2 = page.locator('.ex-card').nth(1).locator('input[data-f="weight"]').first()
  await w2.tap(); await w2.fill('10')
  const r2 = page.locator('.ex-card').nth(1).locator('input[data-f="reps"]').first()
  await r2.tap(); await r2.fill('12')
  await page.locator('.ex-card').nth(1).locator('.check').first().tap()
  await shot('05-rest-timer')
  // try check empty set (should nudge)
  await page.locator('.ex-card').nth(0).locator('.check').nth(1).tap()
  await shot('06-nudge')
  // exercise menu
  await page.locator('.ex-card').nth(0).locator('button[aria-label^="Options"]').tap()
  await shot('07-ex-menu')
  await page.locator('.action', { hasText: 'Cancel' }).count()
  await page.locator('.btn-quiet', { hasText: 'Cancel' }).tap()
  // set menu
  await page.locator('.ex-card').nth(0).locator('.set-kind').nth(0).tap()
  await shot('08-set-menu')
  await page.locator('.btn-quiet', { hasText: 'Cancel' }).tap()
  // add exercise picker
  await page.locator('button', { hasText: 'Add exercise' }).tap()
  await shot('09-picker')
  await page.fill('.sheet input[type=search]', 'curl')
  await shot('10-picker-search')
  await page.getByRole('button', { name: 'Dumbbell Curl Arms · Dumbbell', exact: true }).tap()
  await shot('11-picker-selected')
  await page.locator('.sheet-foot .btn-primary').tap()
  await shot('12-added')
  // Finish
  await page.locator('.live-head .btn-primary').tap()
  await shot('13-finish-prompt')
  await page.locator('.action', { hasText: 'Leave them out' }).tap()
  await shot('14-save-sheet')
  await page.locator('.sheet-foot .btn-primary').tap()
  await page.waitForTimeout(600)
  await shot('15-summary')
  await page.screenshot({ path: OUT + '15b-summary-full.png', fullPage: true })
  console.log('URL', page.url())
  console.log(errors.join('\n') || 'no errors')
  await browser.close()
})()
