const { chromium } = require(process.env.PLAYWRIGHT || '/opt/node22/lib/node_modules/playwright')
const OUT = __dirname + '/shots2/'
require('fs').mkdirSync(OUT, { recursive: true })
;(async () => {
  const browser = await chromium.launch({ executablePath: process.env.CHROMIUM || '/opt/pw-browsers/chromium' })
  const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true, colorScheme: process.env.SCHEME || 'dark' })
  const page = await ctx.newPage()
  const errors = []
  page.on('pageerror', (e) => errors.push('pageerror: ' + e.message))
  page.on('console', (m) => m.type() === 'error' && !m.text().includes('401') && errors.push('console: ' + m.text()))
  const shot = async (n, full) => { await page.waitForTimeout(450); await page.screenshot({ path: OUT + n + '.png', fullPage: !!full }) }
  await page.goto('http://localhost:3000/')
  await page.waitForSelector('.page-head')
  await page.waitForTimeout(800)
  await page.locator('.sync-badge').tap()
  await shot('01-settings-locked', true)
  await page.fill('input[type=password]', 'wrong')
  await page.locator('button', { hasText: 'Connect' }).tap()
  await shot('02-wrong-key')
  await page.fill('input[type=password]', 'testkey')
  await page.locator('button', { hasText: 'Connect' }).tap()
  await page.waitForTimeout(800)
  await shot('03-connected')
  await page.locator('.page-head .icon-btn').first().tap()
  await shot('04-train-with-history', true)
  await page.locator('.tab', { hasText: 'History' }).tap()
  await shot('05-history', true)
  await page.locator('.workout-card').first().tap()
  await shot('06-workout-detail', true)
  await page.locator('.detail-ex-name').first().tap()
  await shot('07-exercise-detail', true)
  await page.locator('.chip', { hasText: 'Est. 1RM' }).tap()
  await shot('08-exercise-1rm')
  await page.locator('.tab', { hasText: 'Exercises' }).tap()
  await shot('09-exercises')
  await page.locator('.tab', { hasText: 'Train' }).tap()
  await page.locator('.plan-card .btn').tap()
  await page.waitForSelector('.live')
  await shot('10-live-with-previous')
  await page.screenshot({ path: OUT + '10b-live-full.png', fullPage: true })
  // log a heavier set to trigger a PR
  const w = page.locator('.ex-card').first().locator('input[data-f="weight"]').first()
  await w.tap(); await w.fill('20')
  await page.locator('.ex-card').first().locator('.check').first().tap()
  await page.locator('.ex-card').first().locator('.check').nth(1).tap()
  await shot('11-live-logged')
  // minimize
  await page.locator('button[aria-label="Minimize workout"]').tap()
  await shot('12-minibar')
  await page.locator('.mini-bar').tap()
  await page.locator('.live-head .btn-primary').tap()
  await page.locator('.action', { hasText: 'Leave them out' }).tap()
  await page.locator('.sheet-foot .btn-primary').tap()
  await page.waitForTimeout(700)
  await shot('13-summary-pr', true)
  console.log(errors.join('\n') || 'no errors')
  await browser.close()
})()
