// Fasting screen (plans, back-dated start, stages, stats, past fasts), target weight,
// the History calendar, the day page (note, weigh-in) and the muscle split on a workout.
const { chromium } = require(process.env.PLAYWRIGHT || '/opt/node22/lib/node_modules/playwright')
const OUT = __dirname + '/shots11/'
require('fs').mkdirSync(OUT, { recursive: true })
;(async () => {
  const browser = await chromium.launch({ executablePath: process.env.CHROMIUM || '/opt/pw-browsers/chromium' })
  for (const scheme of ['dark', 'light']) {
    const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true, colorScheme: scheme })
    await ctx.addInitScript(() => localStorage.setItem('reps-token', 'testkey'))
    const page = await ctx.newPage()
    const errors = []
    page.on('pageerror', (e) => errors.push('pageerror: ' + e.message))
    page.on('console', (m) => m.type() === 'error' && errors.push('console: ' + m.text()))
    const shot = async (n, full) => { await page.waitForTimeout(450); await page.screenshot({ path: OUT + scheme + '-' + n + '.png', fullPage: !!full }) }
    await page.goto('http://localhost:3000/#/body')
    await page.waitForSelector('.fast-card')
    await page.waitForTimeout(1500)
    if (scheme === 'dark') {
      // end any running fast first so we start from idle
      const endBtn = page.locator('.fast-card .btn', { hasText: 'End fast' })
      if (await endBtn.count()) {
        await endBtn.tap()
        await page.waitForSelector('.fast-celebrate')
        await page.goto('http://localhost:3000/#/body')
        await page.waitForTimeout(600)
      }
      await page.locator('.fast-card').scrollIntoViewIfNeeded()
      await shot('01-body-card')
      await page.locator('.fast-card .eyebrow').tap()
      await page.waitForSelector('.fast-screen')
      await shot('02-fast-idle', true)
      await page.locator('.proto-pill').tap()
      await shot('03-plans')
      await page.locator('.proto', { hasText: '18:6' }).tap()
      await page.waitForTimeout(300)
      await page.locator('.link-btn').tap()
      await page.locator('.sheet .chip', { hasText: '2 h ago' }).tap()
      await shot('04-start-earlier')
      await page.locator('.sheet-foot .btn-primary').tap()
      await page.waitForTimeout(600)
      await shot('05-fasting', true)
      await page.locator('.section-head .btn', { hasText: 'Add past fast' }).tap()
      await page.locator('.sheet textarea').fill('Broke it with eggs and coffee')
      await shot('06-add-past')
      await page.locator('.sheet-foot .btn-primary').tap()
      await page.waitForTimeout(500)
      await page.goto('http://localhost:3000/#/body')
      await page.waitForTimeout(600)
      await page.locator('.fast-card').scrollIntoViewIfNeeded()
      await shot('07-body-card-on')
      await page.locator('.target-set, .wgoal').first().scrollIntoViewIfNeeded()
      await page.locator('.target-set, .wgoal').first().tap()
      await page.locator('#target-weight').fill('75')
      await page.locator('.sheet-foot .btn-primary').tap()
      await page.waitForTimeout(400)
      await page.locator('.weight-card').scrollIntoViewIfNeeded()
      await shot('08-weight-target')
    }
    await page.goto('http://localhost:3000/#/history')
    await page.waitForTimeout(600)
    await page.locator('.view-toggle button').nth(1).tap()
    await page.waitForSelector('.cal')
    await shot('09-calendar')
    await shot('10-calendar-full', true)
    const trained = page.locator('.cal-day:has(.cal-num.trained)').first()
    await trained.tap()
    await page.waitForSelector('.day-screen')
    await shot('11-day', true)
    if (scheme === 'dark') {
      await page.locator('.day-card textarea').fill('Slept 6 h. Shoulder fine on presses.')
      await page.locator('#day-weight').fill('82.4')
      await page.locator('.day-card .btn', { hasText: /Log|Update/ }).tap()
      await page.waitForTimeout(900)
      await shot('12-day-edited', true)
      await page.locator('.ds-day:not([disabled])').first().tap()
      await page.waitForTimeout(500)
      await shot('13-other-day', true)
      await page.goBack()
      await page.waitForTimeout(500)
      await page.goto('http://localhost:3000/#/history?view=calendar')
      await page.waitForTimeout(700)
      await shot('14-calendar-after')
      await page.locator('.cal-day:has(.cal-num.trained)').nth(3).tap()
      await page.waitForSelector('.day-workout')
      await page.locator('.day-workout').first().tap()
      await page.waitForTimeout(700)
      const split = page.locator('.split-card')
      if (await split.count()) { await split.scrollIntoViewIfNeeded(); await shot('15-muscle-split') } else console.log('no split card')
      // persistence: note survives reload
      await page.goto('http://localhost:3000/#/history')
      await page.reload()
      await page.waitForTimeout(1200)
      console.log('view remembered:', await page.locator('.cal').count() === 1)
      console.log('note dots:', await page.locator('.cal-dots .lg-note').count())
    } else {
      await page.goto('http://localhost:3000/#/fast')
      await page.waitForTimeout(800)
      await shot('12-fast', true)
    }
    console.log(scheme, errors.join('\n') || 'no errors')
    await ctx.close()
  }
  await browser.close()
})()
