// Coach memory and follow-through: chat with tool calls (memory chips, commitment, proposals),
// approving a routine change, the Memory screen, the weekly review, pre-workout targets and the post-workout takeaway.
// Needs the server running with a Gemini stand-in that returns function calls (see HANDOFF.md, QA).
const { chromium } = require(process.env.PLAYWRIGHT || '/opt/node22/lib/node_modules/playwright')
const OUT = __dirname + '/shots10/'
require('fs').mkdirSync(OUT, { recursive: true })
;(async () => {
  const browser = await chromium.launch({ executablePath: process.env.CHROMIUM || '/opt/pw-browsers/chromium' })
  const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true, colorScheme: 'dark' })
  await ctx.addInitScript(() => localStorage.setItem('reps-token', 'testkey'))
  const page = await ctx.newPage()
  const errors = []
  page.on('pageerror', (e) => errors.push('pageerror: ' + e.message))
  page.on('console', (m) => m.type() === 'error' && errors.push('console: ' + m.text()))
  const shot = async (n, full) => { await page.waitForTimeout(450); await page.screenshot({ path: OUT + n + '.png', fullPage: !!full }) }
  await page.goto('http://localhost:3000/#/coach')
  await page.waitForSelector('.coach-screen')
  await page.waitForTimeout(1500)
  await shot('01-coach-start')
  await page.locator('.composer textarea, .composer input').first().fill('Should I go heavier on squats?')
  await page.locator('.composer .send').tap()
  await page.waitForTimeout(250)
  await shot('02-tool-running')
  await page.waitForSelector('.proposal')
  await page.waitForTimeout(1200)
  await shot('03-answer-with-proposals', true)
  const propBefore = await page.evaluate(() => document.querySelectorAll('.proposal').length)
  await page.locator('.proposal').first().locator('.btn-primary').tap()
  await page.waitForTimeout(700)
  await page.locator('.proposal').nth(1).locator('.btn-secondary').tap()
  await page.waitForTimeout(500)
  await shot('04-approved-dismissed', true)
  console.log('proposals:', propBefore, '| states:', await page.locator('.proposal-state').allInnerTexts())
  await page.locator('.page-head .btn-text').tap()
  await page.waitForSelector('.mem-list')
  await page.waitForTimeout(800)
  await shot('05-memory', true)
  await page.locator('.field textarea').first().fill('Back to a 20 kg goblet squat by December.')
  await page.locator('.btn-primary', { hasText: 'Save profile' }).tap()
  await page.locator('#note-new').fill('Train mornings, fasted.')
  await page.locator('.mem-add .btn', { hasText: 'Add' }).nth(1).tap()
  await page.waitForTimeout(500)
  await shot('06-memory-edited', true)
  // the edited routine should now carry the coach's 14 kg
  await page.goto('http://localhost:3000/#/coach')
  await page.waitForTimeout(800)
  await shot('07-coach-commit-strip-weekly', true)
  const wk = page.locator('.weekly-head')
  if (await wk.count()) { await wk.tap(); await shot('08-weekly-open', true) } else console.log('no weekly card')
  // pre-workout targets
  await page.goto('http://localhost:3000/#/')
  await page.waitForTimeout(800)
  const card = page.locator('.routine-card').first()
  console.log('starting:', (await card.innerText()).split('\n')[0])
  await card.locator('button', { hasText: 'Start' }).tap()
  await page.waitForSelector('.live')
  await page.waitForTimeout(200)
  await shot('09-live-loading')
  await page.waitForSelector('.coach-card:not(.loading)')
  await shot('10-live-targets')
  await page.locator('.coach-card .btn', { hasText: 'Use these targets' }).tap()
  await page.waitForTimeout(400)
  await shot('11-targets-applied', true)
  const ph = await page.locator('.ex-card').first().locator('input').first().getAttribute('placeholder')
  console.log('first weight placeholder after applying:', ph)
  await page.locator('.ex-card').first().locator('.check').first().tap()
  await page.locator('.live-head .btn-primary').tap()
  await page.waitForTimeout(400)
  await shot('12-finish-sheet')
  await page.locator('.sheet-foot .btn-primary').tap()
  await page.waitForTimeout(400)
  await shot('13-summary-loading')
  await page.waitForTimeout(2000)
  await shot('14-summary-takeaway', true)
  await page.goto('http://localhost:3000/#/coach/memory')
  await page.waitForTimeout(1200)
  await shot('15-memory-after', true)
  console.log(errors.join('\n') || 'no errors')
  await browser.close()
})()
