const { chromium } = require(process.env.PLAYWRIGHT || '/opt/node22/lib/node_modules/playwright')
const OUT = __dirname + '/shots3/'
require('fs').mkdirSync(OUT, { recursive: true })
;(async () => {
  const browser = await chromium.launch({ executablePath: process.env.CHROMIUM || '/opt/pw-browsers/chromium' })
  const ctx = await browser.newContext({ viewport: { width: 360, height: 760 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true, colorScheme: 'light' })
  await ctx.addInitScript(() => localStorage.setItem('reps-token', 'testkey'))
  const page = await ctx.newPage()
  const errors = []
  page.on('pageerror', (e) => errors.push('pageerror: ' + e.message))
  page.on('console', (m) => m.type() === 'error' && !m.text().includes('401') && errors.push('console: ' + m.text()))
  const shot = async (n, full) => { await page.waitForTimeout(450); await page.screenshot({ path: OUT + n + '.png', fullPage: !!full }) }
  await page.goto('http://localhost:3000/')
  await page.waitForSelector('.page-head')
  await shot('01-train-light')
  // New routine
  await page.locator('button', { hasText: 'New' }).first().tap()
  await shot('02-new-routine')
  await page.fill('.routine-name-input', 'Upper quick')
  await page.locator('button', { hasText: 'Add exercise' }).tap()
  await page.locator('.chip', { hasText: 'Chest' }).first().tap()
  await shot('03-picker-chest')
  await page.getByRole('button', { name: /^Push-Up Chest/ }).tap()
  await page.getByRole('button', { name: /^Dumbbell Bench Press/ }).tap()
  await shot('04-picker-two')
  await page.locator('.sheet-foot .btn-secondary', { hasText: 'Superset' }).tap()
  await page.waitForTimeout(400)
  const wi = page.locator('.ex-card').nth(1).locator('input[data-f="weight"]').first()
  await wi.tap(); await wi.fill('22.5')
  await shot('05-routine-editor', true)
  await page.locator('.sticky .btn-primary').tap()
  await shot('06-routine-saved', true)
  // Exercises: create custom
  await page.locator('.tab', { hasText: 'Exercises' }).tap()
  await page.fill('input[type=search]', 'cossack squat')
  await shot('07-ex-nomatch')
  await page.locator('button', { hasText: 'Create it' }).tap()
  await shot('08-ex-form')
  await page.locator('.type-opt', { hasText: 'Reps only' }).tap()
  await page.locator('.chips-wrap .chip', { hasText: 'Legs' }).first().tap()
  await page.locator('.sheet-foot .btn-primary').tap()
  await shot('09-ex-created')
  // lb units
  await page.goto('http://localhost:3000/#/settings')
  await page.locator('.segmented button', { hasText: 'lb' }).tap()
  await page.goto('http://localhost:3000/#/history')
  await page.waitForTimeout(500)
  await page.locator('.workout-card').first().tap()
  await shot('10-detail-lb')
  await page.locator('button[aria-label="Workout options"]').tap()
  await page.locator('.action', { hasText: 'Edit workout' }).tap()
  await shot('11-edit-workout', true)
  await page.locator('.sticky .btn-text').tap()
  // empty-state check: Train live with empty workout
  await page.goto('http://localhost:3000/#/train')
  await page.locator('button', { hasText: 'Start empty workout' }).tap()
  await shot('12-empty-live')
  await page.locator('.live-head .btn-primary').tap()
  await shot('13-empty-finish')
  await page.locator('.modal .btn-danger').tap()
  await page.waitForTimeout(400)
  // offline reload
  await ctx.setOffline(true)
  await page.reload()
  await page.waitForSelector('.page-head', { timeout: 5000 }).catch(() => errors.push('offline reload failed'))
  await shot('14-offline')
  console.log(errors.join('\n') || 'no errors')
  await browser.close()
})()
